spring:
    datasource:
        hikari:
            jdbcUrl: jdbc:mysql://dbauroraclarodev.cx053an4mesk.us-east-1.rds.amazonaws.com:3306/dbclaroclubdev
            username: adminclaroclub
            password: 
            driver-class-name: com.mysql.jdbc.Driver
            connectionTimeout: 10000
            maxLifetime: 3600000
            maximumPoolSize: 20
            minimumIdle: 1
            idleTimeout: 10000
    jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
#IDF
category:
    codigo:
        idf0: 0
        idf1: 1
        idf2: 2
        idf3: 3
        idt1: -1
        idt2: -2
    mensaje:
        idf0: Operación Exitosa
        idf1: Se debe enviar campos obligatorios
        idf2: No se obtuvo resultados de categorias
        idf3: Ocurrió un error inesperado
        idt1: Error de timeout en la bd $bd
        idt2: Error de disponibilidad en la bd $bd